name: Build Package

on: [push, pull_request, workflow_dispatch]

jobs:
  linux_build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2.2.2
        with:
          python-version: 3.9

      - name: Build package
        run: |
          python setup.py sdist
  
      - name: lint package
        run: |
          pip install twine
          twine check dist/*

      - name: Install package
        run: |
          pip install dist/*.tar.gz --disable-pip-version-check

      - name: Unit testing
        run: |
          pip install -r requirements_tests.txt --disable-pip-version-check
          pytest -v

      - name: Upload to PyPi
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          pip install twine
          twine upload --skip-existing dist/*
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.TWINE_TOKEN }}
